env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
plugins:
  - mocha
parserOptions:
  ecmaVersion: 12
rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  no-console: 0
